esphome:
  name: julie-light
  platform: ESP32
  board: esp-wrover-kit

logger:
  level: DEBUG

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:

mqtt:
  broker: 192.168.2.159

light:
  - platform: rgb
    name: "Julie Light"
    red: red
    green: green
    blue: blue

output:
  - platform: ledc
    id: red
    pin: GPIO19
  - platform: ledc
    id: green
    pin: GPIO23
  - platform: ledc
    id: blue
    pin: GPIO5
